name: Code Health Check

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3

      - name: Run server tests
        working-directory: server
        run: |
          cd server
          npm install
          node index.js & sleep 10

      - name: Run client build (sanity check)
        working-directory: client
        run: |
          cd client
          npm install
          npm run build || exit 1
